CREATE
OR REPLACE TABLE todos (
       id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       body VARCHAR(255) NOT NULL,
       priority TINYINT UNSIGNED,
       due DATE DEFAULT NULL,
       completed BOOLEAN NOT NULL DEFAULT 0,
       created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
       deleted_at DATETIME DEFAULT NULL
);