CREATE
OR REPLACE TABLE todos (
       id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
       body VARCHAR(255) NOT NULL,
       priority TINYINT UNSIGNED,
       due DATE DEFAULT NULL,
       created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);